name: Update Codewars Stats

on:
  schedule:
    - cron: '0 * * * *'  # jede Stunde
  workflow_dispatch:

jobs:
  update-codewars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Verwende GITHUB_TOKEN statt PAT_TOKEN für checkout
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Codewars SVG
        run: python scripts/generate_codewars_svg.py

      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add codewars_stats.svg
          git diff-index --quiet HEAD || git commit -m "Update Codewars stats"
          git push
